// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUd8ePaoMjCukwnVhEQdzTr2l4tofaeBE',
    appId: '1:795830182196:web:51dbe79ded118899f80561',
    messagingSenderId: '795830182196',
    projectId: 'chordnerd',
    authDomain: 'chordnerd.firebaseapp.com',
    storageBucket: 'chordnerd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL616t8ij0HfOpjpEpbm1lSz2Z1FcK9Vo',
    appId: '1:795830182196:android:09d65739d538a3c2f80561',
    messagingSenderId: '795830182196',
    projectId: 'chordnerd',
    storageBucket: 'chordnerd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnFkzboOIY-3K600W7hr0WM2Szfuu_FK0',
    appId: '1:795830182196:ios:b81751905c669a3ff80561',
    messagingSenderId: '795830182196',
    projectId: 'chordnerd',
    storageBucket: 'chordnerd.firebasestorage.app',
    iosClientId: '795830182196-uohubc9t00167cli7c3hb1i00tf8tkth.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnFkzboOIY-3K600W7hr0WM2Szfuu_FK0',
    appId: '1:795830182196:ios:b81751905c669a3ff80561',
    messagingSenderId: '795830182196',
    projectId: 'chordnerd',
    storageBucket: 'chordnerd.firebasestorage.app',
    iosClientId: '795830182196-uohubc9t00167cli7c3hb1i00tf8tkth.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUd8ePaoMjCukwnVhEQdzTr2l4tofaeBE',
    appId: '1:795830182196:web:4d0a84f855bf30bff80561',
    messagingSenderId: '795830182196',
    projectId: 'chordnerd',
    authDomain: 'chordnerd.firebaseapp.com',
    storageBucket: 'chordnerd.firebasestorage.app',
  );
}
