import 'package:chord_nerd/firebase_options.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'app/theme/app_colors.dart';
import 'app/theme/app_theme.dart';
import 'services/auth_service.dart';
import 'screens/auth/login_screen.dart';
import 'screens/main/main_navigation.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    // TODO: pass `options: DefaultFirebaseOptions.currentPlatform` here
    // once firebase_options.dart exists (generated by `flutterfire configure`)
    options: DefaultFirebaseOptions.currentPlatform
  );

  runApp(
    const ProviderScope(
      child: ChordNerdApp(),
    ),
  );
}

class ChordNerdApp extends StatelessWidget {
  const ChordNerdApp({super.key});

  @override
  Widget build(BuildContext context) {
    // AppColors.mode is a ValueNotifier<bool> (true = dark). Listening to
    // it here means toggling it anywhere in the app (e.g. a Settings
    // switch) rebuilds the whole MaterialApp with the matching theme —
    // light by default, dark once switched on.
    return ValueListenableBuilder<bool>(
      valueListenable: AppColors.mode,
      builder: (context, isDark, _) {
        return MaterialApp(
          title: 'Chord Nerd',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.current,
          home: const _AuthGate(),
        );
      },
    );
  }
}

/// Shows LoginScreen when signed out, MainNavigation (the full tab shell)
/// when signed in.
class _AuthGate extends StatelessWidget {
  const _AuthGate();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: AuthService.authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        final user = snapshot.data;
        if (user == null) {
          return const LoginScreen();
        }
        return const MainNavigation();
      },
    );
  }
}
