import 'package:chord_nerd/app/Theme/app_theme.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'screens/auth/login_screen.dart';
import 'screens/profile_screen.dart';
import 'services/auth_service.dart';
import 'firebase_options.dart';
// TODO: import 'app/router/app_router.dart' and swap ProfileScreen below for
// the full bottom-tab navigator (Dashboard/Search/Library/Profile) once
// those screens exist.

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
      // TODO: pass `options: DefaultFirebaseOptions.currentPlatform` here
      // once firebase_options.dart exists (generated by `flutterfire configure`)
      options: DefaultFirebaseOptions.currentPlatform);

  runApp(
    const ProviderScope(
      child: ChordNerdApp(),
    ),
  );
}

class ChordNerdApp extends StatelessWidget {
  const ChordNerdApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Chord Nerd',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.dark,
      home: const _AuthGate(),
    );
  }
}

/// Shows LoginScreen when signed out, ProfileScreen when signed in.
/// ProfileScreen is a stand-in here for the full tab navigator until
/// Dashboard/Search/Library exist.
class _AuthGate extends StatelessWidget {
  const _AuthGate();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: AuthService.authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        final user = snapshot.data;
        if (user == null) {
          return const LoginScreen();
        }
        return const ProfileScreen();
      },
    );
  }
}
