import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

import 'app/theme/app_theme.dart';
import 'screens/auth/login_screen.dart';
import 'firebase_options.dart';
// TODO: import 'app/router/app_router.dart' once auth-state routing is built
// TODO: import 'screens/auth/login_screen.dart' once built

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    // TODO: pass `options: DefaultFirebaseOptions.currentPlatform` here
    // once firebase_options.dart exists (generated by `flutterfire configure`)
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    const ProviderScope(
      child: ChordNerdApp(),
    ),
  );
}

class ChordNerdApp extends StatelessWidget {
  const ChordNerdApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Chord Nerd',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.dark,
      // TODO: replace `home` with AppRouter (StreamBuilder on
      // FirebaseAuth.authStateChanges()) once login/register screens exist —
      // for now this is a placeholder so the app boots and shows the theme.
      home: const LoginScreen(),
    );
  }
}
